import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';

class ResearchStep {
  const ResearchStep({required this.label, this.done = false});

  final String label;
  final bool done;

  ResearchStep copyWith({bool? done}) => ResearchStep(label: label, done: done ?? this.done);
}

class SourceItem {
  const SourceItem({required this.title, required this.publisher, required this.credibility});

  final String title;
  final String publisher;
  final String credibility;
}

class ResearchState {
  const ResearchState({
    this.query = '',
    this.steps = const [],
    this.sources = const [],
    this.report = '',
    this.isRunning = false,
  });

  final String query;
  final List<ResearchStep> steps;
  final List<SourceItem> sources;
  final String report;
  final bool isRunning;

  ResearchState copyWith({
    String? query,
    List<ResearchStep>? steps,
    List<SourceItem>? sources,
    String? report,
    bool? isRunning,
  }) {
    return ResearchState(
      query: query ?? this.query,
      steps: steps ?? this.steps,
      sources: sources ?? this.sources,
      report: report ?? this.report,
      isRunning: isRunning ?? this.isRunning,
    );
  }
}

const _planLabels = ['Planning', 'Searching the web', 'Reading sources', 'Cross-checking facts', 'Writing report'];

const _mockSources = [
  SourceItem(title: 'Global EV battery outlook 2026', publisher: 'IEA', credibility: 'Government'),
  SourceItem(title: 'Lithium supply constraints', publisher: 'Nature Energy', credibility: 'Academic'),
  SourceItem(title: 'Battery makers race for nickel', publisher: 'Reuters', credibility: 'News'),
];

/// Drives the Active Research screen: a scripted plan, progressively
/// "found" sources, and a streamed report. A placeholder for the real
/// FastAPI + LangGraph agent (web search, document reading, report
/// writing tools) described in the roadmap.
class ResearchController extends StateNotifier<ResearchState> {
  ResearchController() : super(const ResearchState());

  Future<void> startResearch(String query) async {
    state = ResearchState(
      query: query,
      steps: _planLabels.map((l) => ResearchStep(label: l)).toList(),
      isRunning: true,
    );

    for (var i = 0; i < state.steps.length; i++) {
      await Future<void>.delayed(const Duration(milliseconds: 500));
      final steps = [...state.steps];
      steps[i] = steps[i].copyWith(done: true);
      state = state.copyWith(steps: steps);

      if (i == 1) {
        state = state.copyWith(sources: _mockSources);
      }
      if (i == _planLabels.length - 1) {
        await _streamReport(query);
      }
    }

    state = state.copyWith(isRunning: false);
  }

  Future<void> _streamReport(String query) async {
    final report = 'Research report: $query\n\n'
        'This is a placeholder report generated by the mock research agent. '
        'A real run would ground every claim in the sources listed alongside it, '
        'produced by web search, document reading, and cross-checking tools '
        'orchestrated by the FastAPI + LangGraph backend.';

    final words = report.split(' ');
    var buffer = '';
    for (final word in words) {
      await Future<void>.delayed(const Duration(milliseconds: 25));
      buffer = buffer.isEmpty ? word : '$buffer $word';
      state = state.copyWith(report: buffer);
    }
  }
}

final researchControllerProvider = StateNotifierProvider<ResearchController, ResearchState>((ref) {
  return ResearchController();
});
